// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starshine.EntityFrameworkCore;
using Starshine.EntityFrameworkCore.Test;

#nullable disable

namespace Starshine.TestProject.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20240706021423_InitTable")]
    partial class InitTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Starshine_DatabaseProvider", EFCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Starshine.EntityFrameworkCore.Test.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasComment("创建者id");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("删除时间");

                    b.Property<long>("DeleterId")
                        .HasColumnType("bigint")
                        .HasComment("删除人id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("最后修改时间");

                    b.Property<long>("UpdaterId")
                        .HasColumnType("bigint")
                        .HasComment("最后修改人id");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SysUser");
                });
#pragma warning restore 612, 618
        }
    }
}
